/**
* This file is auto-generated by nestjs-proto-gen-ts
*/
import * as google from 'google-protobuf'
import { ApiProperty } from '@nestjs/swagger'
import { Metadata } from '@grpc/grpc-js'

const enumType = (o) => Object.keys(o).filter(k => Number.isNaN(parseInt(k)))

export namespace inventory {
    export enum ServingStatus {
        UNKNOWN = 0,
        SERVING = 1,
        NOT_SERVING = 2,
    }
    export class HealthCheckRequest {
        @ApiProperty({ type: () => String }) service?: string;
    }
    export class HealthCheckResponse {
        @ApiProperty({ type: () => String, enum: enumType(inventory.ServingStatus), enumName: "ServingStatus" }) status?: inventory.ServingStatus;
    }
    export interface Health {
        check(data: HealthCheckRequest, metadata?: Metadata): Promise<HealthCheckResponse>;
    }
}

