auth:
  rest:
    port: 3001
    url: http://localhost:3001
  grpc:
    url: 0.0.0.0:5001
  graphql:
    url: /api/v1/auth/graphql
inventory:
  rest:
    port: 3002
    url: http://localhost:3002
  grpc:
    url: 0.0.0.0:5002
    port: 5002
  graphql:
    url: /api/v1/inventory/graphql
user:
  rest:
    port: 3003
    url: http://localhost:3003
  grpc:
    url: 0.0.0.0:5003
  graphql:
    url: /api/v1/user/graphql