mutation upsertInventory {
  upsertInventory(
    input: {
      name: "Purina1"
      description: "26kg"
      createdBy: "System"
      inventoryTypeId: "41829212-ab69-47aa-8dd6-d079fd3e9b8d"
      brandTypeId: "7e05f44a-575f-4d46-b55b-86ef0d80353f"
    }
  ) {
    id
  }
}

query getInventories {
  getInventories(
    params: { search: "P", type: "", brand: "", limit: 30, pageNo: 1 }
  ) {
    inventories {
      id
      name
      amount
      sold
      price
      inventoryType {
        name
      }
      brandType {
        name
      }
      description
      expiryDate
      createdBy
      createdAt
      updatedBy
      updatedAt
    }
    pageNo
    pageLimit
    totalPage
    totalRow
  }
}

query getInventory {
  getInventory(id: "a8b094a0-6627-4275-a7bd-464ea162fa2d") {
    id
    name
    description
    createdBy
    createdAt
    updatedBy
    updatedAt
  }
}

query getInventoryTypes {
  getInventoryTypes {
    id
    name
    description
    createdBy
    createdAt
    updatedBy
    updatedAt
  }
}

query getInventoryType {
  getInventoryType(id: "530d26db-a57a-42c9-9a06-b39bb20d2540") {
    id
    name
    description
    createdBy
    createdAt
    updatedBy
    updatedAt
  }
}

query getBrandTypes {
  getBrandTypes {
    id
    name
    description
    createdBy
    createdAt
    updatedBy
    updatedAt
  }
}

query getBrandType {
  getBrandType(id: "530d26db-a57a-42c9-9a06-b39bb20d2540") {
    id
    name
    description
    createdBy
    createdAt
    updatedBy
    updatedAt
  }
}

mutation upsertInventoryType {
  upsertInventoryType(
    input: { id: "", name: "FoodDog", description: "Dog", createdBy: "system" }
  ) {
    id
  }
}

mutation upsertBrandType {
  upsertBrandType(
    input: { id: "", name: "KANIN", description: "Cat", createdBy: "system" }
  ) {
    id
  }
}

mutation deleteBrandType {
  deleteBrandType(id: "2ce80cee-2215-40c5-9147-42894f5b5a4e") {
    id
  }
}

mutation deleteInventoryType {
  deleteInventoryType(id: "97d6ef10-1f5e-4890-9e76-fa171081891d") {
    id
  }
}

mutation deleteInventory {
  deleteInventory(id: "a8b094a0-6627-4275-a7bd-464ea162fa2d") {
    id
  }
}
