mutation upsertInventory {
  upsertInventory(
    input: {
      name: "Purina29"
      description: "26kg"
      createdBy: "System"
      inventoryTypeId: "8918abd5-734f-42ab-98e1-07d2640e255f"
      brandTypeId: "e52bcd56-78fe-4dcb-bb5f-00dab03bb73e"
    }
  ) {
    id
  }
}

query getInventories {
  getInventories(params: { search: "", type:[], brand:["21ec26db-eed2-4d67-aeb2-703be35219cd","fa737cdb-0acb-4fe2-98c1-ce5b76715307"] pageNo:1 ,limit: 30  }) {
    inventories{
      id
    name
    amount
    sold
    price
    inventoryType{
    name
  }
    brandType{
      name
    }
    description
    expiryDate
    createdBy
    createdAt
    updatedBy
    updatedAt
    }
    pageNo,
    pageLimit,
    totalPage,
    totalRow
  }
}

query getInventory {
  getInventory(id: "a8b094a0-6627-4275-a7bd-464ea162fa2d") {
    id
    name
    description
    createdBy
    createdAt
    updatedBy
    updatedAt
  }
}

query getInventoryTypes {
  getInventoryTypes(params: { search: "", offset:0 ,limit: 20  }) {
    id
    name
    description
    createdBy
    createdAt
    updatedBy
    updatedAt
  }
}

query getInventoryType {
  getInventoryType(id: "530d26db-a57a-42c9-9a06-b39bb20d2540") {
    id
    name
    description
    createdBy
    createdAt
    updatedBy
    updatedAt
  }
}

query getBrandTypes {
  getBrandTypes (params: { search: "K", offset:0 ,limit: 20  }){
    id
    name
    description
    createdBy
    createdAt
    updatedBy
    updatedAt
  }
}

query getBrandType {
  getBrandType(id: "530d26db-a57a-42c9-9a06-b39bb20d2540") {
    id
    name
    description
    createdBy
    createdAt
    updatedBy
    updatedAt
  }
}

mutation upsertInventoryType {
  upsertInventoryType(
    input: { id: "", name: "FishFood32", description: "Fish", createdBy: "system" }
  ) {
    id
  }
}

mutation upsertBrandType {
  upsertBrandType(
    input: { id: "", name: "Hills", description: "Cat", createdBy: "system" }
  ) {
    id
  }
}

mutation deleteBrandType {
  deleteBrandType(id: "e52bcd56-78fe-4dcb-bb5f-00dab03bb73e") {
    id
  }
}

mutation deleteInventoryType {
  deleteInventoryType(id: "97d6ef10-1f5e-4890-9e76-fa171081891d") {
    id
  }
}

mutation deleteInventory {
  deleteInventory(id: "431967cb-bdb0-4b86-8062-b06949eb3e0d") {
    id
  }
}
