/**
* This file is auto-generated by nestjs-proto-gen-ts
*/
import * as google from 'google-protobuf'
import { ApiProperty } from '@nestjs/swagger'
import { Metadata } from '@grpc/grpc-js'

const enumType = (o) => Object.keys(o).filter(k => Number.isNaN(parseInt(k)))

export namespace inventory {
}

