/**
* This file is auto-generated by nestjs-proto-gen-ts
*/
import * as google from 'google-protobuf'
import { ApiProperty } from '@nestjs/swagger'
import { Metadata } from '@grpc/grpc-js'

const enumType = (o) => Object.keys(o).filter(k => Number.isNaN(parseInt(k)))

export namespace inventory {
    export class InventoryName {
        @ApiProperty({ type: () => String }) id?: string;
        @ApiProperty({ type: () => String }) name?: string;
    }
    export class InventoryNameList {
        @ApiProperty({ type: () => [inventory.InventoryName] }) inventoryName?: inventory.InventoryName[];
    }
    export interface InventoryGrpcService {
        getInventoryNames(data: EmptyRequest, metadata?: Metadata): Promise<InventoryNameList>;
        tester(data: EmptyRequest, metadata?: Metadata): Promise<InventoryNameList>;
    }
    // tslint:disable-next-line:no-empty-interface
    export class EmptyRequest {
    }
}

